# Site settings
title: Mushank
SEOTitle: Mushank | Jack's Blog
header-img: img/home-bg.jpg
email: mushank@Gmail.com
description: "关于移动开发与设计、生活与艺术 | Mushank, Mobile Dev & Design, Life & Art | 这里是 @Jack 的个人博客，与你一起发现更大的世界。"
keyword: "Jack, Mushank, Blog"
url: "http://127.0.0.1:4000"            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     mushank
# zhihu_username:     mushank
github_username:    mushank
# twitter_username:   mushankkk
# facebook_username:  mushank



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
# disqus_username: mushank

# Duoshuo settings
duoshuo_username: mushank
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-87707150-1'            # Format: UA-xxxxxx-xx
# ga_domain: mushank.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "人生如逆旅，我亦是行人<br>离开世界之前，一切皆是修行"
sidebar-avatar: /img/avatar-jack.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "ojbc.io",
        href: "https://www.objc.io/"
    },{
        title: "objccn,io",
        href: "https://objccn.io/"
    },{
        title: "OneV's Den",
        href: "https://onevcat.com/"
    },{
        title: "Casa Taloyum",
        href: "http://casatwy.com/"
    },{
        title: "唐巧的技术博客",
        href: "http://blog.devtang.com/"
    },{
        title: "Kevin",
        href: "http://blog.zhowkev.in/"
    },{
        title: "sunnyxx的技术博客",
        href: "http://blog.sunnyxx.com/"
    },{
        title: "Draveness",
        href: "http://draveness.me/"
    },{
        title: "刘坤的技术博客",
        href: "https://blog.cnbluebox.com/"
    }
]
